### ISSUE TITLE
Test server not fully running

### ISSUE THREAD

**Issue by paulhiggs** [cta-wave/WMAS2017#1]
I followed the instructions to install a local test server and in one window run `./wave start` and in another run `./wpt start`

The DUT can access test-server:8050 but when I start the tests get a error indicating that the test cannot be retrieved from test-server:8000.

**Comment by mlasak** [comment]
Hi, thank you for checking. We added some more information on the required software:
```
Python 2.7+ (but not Python 3.x)
Node.js 8.x.x (LTS recommended)
Git 2.4+ (should support sparse checkout)
Bash script support (on windows we recommend Git BASH)
```
Please, can you confirm that the host you try to run on does meet the requirements?  
Beside this, can you check if your /etc/hosts file was configured properly? It should contain this entries:
```
127.0.0.1	web-platform.test
127.0.0.1	www.web-platform.test
127.0.0.1	xn--n8j6ds53lwwkrqhv28a.web-platform.test
127.0.0.1	xn--lve-6lad.web-platform.test
127.0.0.1	www2.web-platform.test
127.0.0.1	www1.web-platform.test
0.0.0.0	nonexistent-origin.web-platform.test
```

If none of this above does lead to success, please post the error message for further analysis.

**Comment by paulhiggs** [comment]
Following versions are installed along with `bash`.

~ $ python --version
Python 2.7.13
~ $ node -v
v10.6.0
~ $ git --version
git version 2.11.0

hosts file  contains the same lines - they were added with the `./wpt make_hosts_file` command

127.0.0.1       web-platform.test
127.0.0.1       www.web-platform.test
127.0.0.1       xn--n8j6ds53lwwkrqhv28a.web-platform.test
127.0.0.1       xn--lve-6lad.web-platform.test
127.0.0.1       www2.web-platform.test
127.0.0.1       www1.web-platform.test
0.0.0.0 nonexistent-origin.web-platform.test


debug log messages from `./wpt serve'

DEBUG:web-platform-tests:Going to use port 46487 to check subdomains
DEBUG:web-platform-tests:Route pattern: ^/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.py)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.asis)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.any\.worker\.js)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.any\.html)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.window\.html)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.worker\.html)$
DEBUG:web-platform-tests:Route pattern: ^/serve\.py$
DEBUG:web-platform-tests:Route pattern: ^/(?P<spec>[^/]+)/tools/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/tools/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/\_certs/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/nodejs/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/tools/runner/update\_manifest\.py$
DEBUG:web-platform-tests:Route pattern: ^/tools/runner/(.*)$
DEBUG:web-platform-tests:Using default configuration
INFO:web-platform-tests:Starting http server on web-platform.test:46487
DEBUG:web-platform-tests:GET /
DEBUG:web-platform-tests:Found handler FileHandler
DEBUG:web-platform-tests:200 GET / (None) 0
DEBUG:web-platform-tests:GET /
DEBUG:web-platform-tests:Found handler FileHandler
DEBUG:web-platform-tests:200 GET / (None) 0
DEBUG:web-platform-tests:GET /
DEBUG:web-platform-tests:Found handler FileHandler
DEBUG:web-platform-tests:200 GET / (None) 0
DEBUG:web-platform-tests:GET /
DEBUG:web-platform-tests:Found handler FileHandler
DEBUG:web-platform-tests:200 GET / (None) 0
DEBUG:web-platform-tests:GET /
DEBUG:web-platform-tests:Found handler FileHandler
DEBUG:web-platform-tests:200 GET / (None) 0
DEBUG:web-platform-tests:GET /
DEBUG:web-platform-tests:Found handler FileHandler
DEBUG:web-platform-tests:200 GET / (None) 0
DEBUG:web-platform-tests:Going to use port 49365 for stash
DEBUG:web-platform-tests:Using ports: defaultdict(<type 'list'>, {u'http': [8000, 57869], u'wss': [55845], u'ws': [33103], u'https': [8443], u'wave': [8050]})
DEBUG:web-platform-tests:Route pattern: ^/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.py)$
DEBUG:web-platform-tests:Route pattern: ^/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.asis)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.any\.worker\.js)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.py)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.any\.html)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.asis)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.window\.html)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.any\.worker\.js)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.worker\.html)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.any\.html)$
DEBUG:web-platform-tests:Route pattern: ^/serve\.py$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.window\.html)$
DEBUG:web-platform-tests:Route pattern: ^/(?P<spec>[^/]+)/tools/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/tools/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.worker\.html)$
DEBUG:web-platform-tests:Route pattern: ^/\_certs/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.py)$
DEBUG:web-platform-tests:Route pattern: ^/serve\.py$
DEBUG:web-platform-tests:Route pattern: ^/nodejs/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.asis)$
DEBUG:web-platform-tests:Route pattern: ^/(?P<spec>[^/]+)/tools/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/tools/runner/update\_manifest\.py$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.any\.worker\.js)$
DEBUG:web-platform-tests:Route pattern: ^/tools/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/tools/runner/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.any\.html)$
INFO:web-platform-tests:Starting http server on web-platform.test:8000
DEBUG:web-platform-tests:Route pattern: ^/\_certs/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.window\.html)$
DEBUG:web-platform-tests:Route pattern: ^/nodejs/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/(.*\.worker\.html)$
DEBUG:web-platform-tests:Route pattern: ^/serve\.py$
DEBUG:web-platform-tests:Route pattern: ^/tools/runner/update\_manifest\.py$
DEBUG:web-platform-tests:Route pattern: ^/(?P<spec>[^/]+)/tools/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/tools/runner/(.*)$
INFO:web-platform-tests:Starting http server on web-platform.test:57869
DEBUG:web-platform-tests:Route pattern: ^/tools/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/\_certs/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/nodejs/(.*)$
DEBUG:web-platform-tests:Route pattern: ^/tools/runner/update\_manifest\.py$
DEBUG:web-platform-tests:Route pattern: ^/tools/runner/(.*)$
INFO:web-platform-tests:Starting http server on web-platform.test:8443
INFO:mod_pywebsocket.standalone.WebSocketServer:Create socket on: (2, 1, 6, '', ('127.0.0.1', 55845))
INFO:mod_pywebsocket.standalone.WebSocketServer:Bind on: (2, 1, 6, '', ('127.0.0.1', 55845))
INFO:mod_pywebsocket.standalone.WebSocketServer:Listen on: (2, 1, 6, '', ('127.0.0.1', 55845))
INFO:mod_pywebsocket.standalone.WebSocketServer:Create socket on: (2, 1, 6, '', ('127.0.0.1', 33103))
INFO:mod_pywebsocket.standalone.WebSocketServer:Bind on: (2, 1, 6, '', ('127.0.0.1', 33103))
INFO:mod_pywebsocket.standalone.WebSocketServer:Listen on: (2, 1, 6, '', ('127.0.0.1', 33103))


log messages from `./wave start`

Starting Wave Server ...
Wave Server started on port 8050
TEST 2dcontext/compositing/2d.composite.canvas.copy.html
TIMEOUT 2dcontext/compositing/2d.composite.canvas.copy.html


Using my PC as a DUT the errror is
![capture](https://user-images.githubusercontent.com/3158807/42628812-40775cb4-859f-11e8-83d5-fd66961dd9ef.PNG)

**Comment by mlasak** [comment]
Ok, thanks for sharing the screenshot. You pointed us to an error in the README, corrected now. Please open your Web browser at http://web-platform.test:8050 (this is the correct start/entry page, if default config was not changed).

Explanation: The python Web server binds to web-platform.test:8000 which resolves to 127.0.0.1, so starting with 192.x.x.x or anything else will not work. The Node.js hosted start/entry page and the session service behind does bind to 0.0.0.0:8050, therefore you could as well use the other interface address.

**Comment by paulhiggs** [comment]
I do not understand this response. I installed the test server on a linux machine that only has SSH (its a linux server so no Browser). The browser screen shot is from the DUT.

**Comment by mlasak** [comment]
Ok, understand you setup now. You would like to host the runner and tests and access it from remote. The original ```Web platform test``` project is not designed to be used with IP addresses. So to use in a distributed setup you need to configure a DNS server appropriately. Simply, configure the A records appropriately. Please take the generated entries for the local /etc/hosts as guidance and replace 120.0.0.1 with your server IP and web-platform.test with your domain name to administer DNS.

**Comment by paulhiggs** [comment]
OK. so I changed the `/etc/hosts` file and replaced the 127.0.0.1 with the the IP address of the test server and all works OK. I am able to enter an IP address into the DUT and the test systems works OK (with the exception of secure test functions)

![2018-07-16 22 19 15](https://user-images.githubusercontent.com/3158807/42781418-1a05c39a-8914-11e8-8760-2821f6f9ae70.jpg)

From my portable lab n Ljubljana - Raspberry Pi hosts the test server and reporting app Laptop runs DUT in Chrome

**Comment by paulhiggs** [comment]
Closing this issue

**Comment by mlasak** [comment]
Thanks Paul! We very much appreciate that you have checked the project. 

I like your portable lab and i am thankful that the IT world was given RasPis :)
