### ISSUE TITLE
Ability to run the "passing subset" on local hosted test tool

### ISSUE THREAD

**Issue by andyburras** [cta-wave/WMAS2017#19]
I've followed the https://github.com/cta-wave/WMAS2017/ README.md instructions to install and run the test system.
I'm struggling to understand how to run the actual subset of passing tests?

If I run the tests with http://web-platform.test:8050 on the latest Firefox, it appears to run all tests and reports many failures.

If I constrain the test run to e.g. http://web-platform.test:8050?path=/fullscreen , it only runs the 'fullscreen' tests but again seems to run those that fail too?

![wmas2017_fullscreen_firefox](https://user-images.githubusercontent.com/28623246/45815164-c38f4a00-bccf-11e8-8c67-50bae7c45349.jpg)
![wmas2017-all-firefox](https://user-images.githubusercontent.com/28623246/45815166-c38f4a00-bccf-11e8-89aa-27067e268c4d.png)

How do I run the subset that pass on all 4 browsers? Is there a step needed to generate some constrained manifest?

There is also a 'types' parameter which can be a combination of 'testharness', 'manual' and 'reftest'.
To run a full "passing" subset, do all three of these need to be specified?

I can't find anything in the 'docs' directory or the README.

**Comment by squapp** [comment]
Thanks for the feedback!
Currently, filtering (e.g. only test cases that passed on all 4 browsers) is only available via the hosted instance: https://webapitests2017.ctawave.org . That is where we conducted the tests for the 4 browsers.
Filtering requires existing test results. We'll have to think about the best way to make the test results available to this repo. Meanwhile, I would suggest to do filtered testing on the hosted instance.

**Comment by andyburras** [comment]
Just trried it on the online instance with Firefox 62.0. Selected only 'Fullscreen' and selected "All browsers". But I'm still seeing a result of 90 Pass and 34 Fail (identical to locally hosted version).

**Comment by andyburras** [comment]
RE: "_We'll have to think about the best way to make the test results available to this repo_."

Is there any update on this? The combination of this and https://github.com/cta-wave/WMAS2017/issues/20 is preventing us being able to use the tool on our projects to determine if a device is WMAS2017 compatible.

**Comment by squapp** [comment]
yes, we will export the test results (of the 4 browsers) from the running instance.
These results can then be imported to local installations.

**Comment by squapp** [comment]
this feature was added in the latest commit: 
https://github.com/cta-wave/WMAS2017/commit/bf81c0e4ec55edae0f02e068475bbe5a4619e60e
