### ISSUE TITLE
Ability to run 'manual' and 'reftest' tests online

### ISSUE THREAD

**Issue by andyburras** [cta-wave/WMAS2017#20]
On a local installation I can run e.g.

> http://web-platform.test:8050/?path=/fullscreen&types=manual

But I can't see how to run the 'manual' and 'reftest' tests on the hosted online version? The tool seems to always default to 'testharness'.

**Comment by squapp** [comment]
yes, we restricted the hosted online version to 'testharness' tests, because 'manual' and 'reftest' tests require user interaction (e.g. clicking buttons). We cannot guarantee that this user interaction works across embedded devices, which have different input mechanisms. Modifying all 'manual' and 'reftest' tests, which were written in different ways, was out of scope.
However, running 'manual' and 'reftests' on a local installation is possible and there might be embedded devices that are compatible with the input mechanisms of the tests.

**Comment by andyburras** [comment]
But that does mean that it is not possible to handle the use case of "Is my device compatible with WMAS2017" ?

The solution needs to run all tests in the subset that passed on all four browsers to be able to establish conformance.

**Comment by andyburras** [comment]
It was always acknowledged there would be gaps, and making the test suite equal to those that pass on all 4 browsers was itself a pragmatic approach. However my understanding was that the intent was always that it should be all tests that pass on all 4, which includes manual as well as automatic.

**Comment by squapp** [comment]
thanks, I get your point. We'll discuss this. Meanwhile, I'll tag this as a feature request.

Would be great if you could share your experience with ‘manual’ and ‘reftest’ tests on embedded devices.

**Comment by andyburras** [comment]
I tried running the test subset that pass on all 4 browsers, on a recent top-end TV.
I was able to run the automatic tests direct from the ctawave.org site (with a 97% pass rate).

However, I couldn't work out how to run my locally hosted test runner on the TV, and so run the manual and reftests?
The github instructions say "Open in Web browser (on the same host): http://web-platform.test:8050",
but I need to point the embedded device at the test platform running on a different host.

Do I need to change configuration settings to get the tool to listen on a different address than 127.0.0.1?
I couldn't find anything in the documentations.

**Comment by squapp** [comment]
please check #1 
with a remote host, you will need to configure your DNS

**Comment by andyburras** [comment]
I don't think I'm following. I can't edit the DNS on the corporate LAN, and wouldn't want to be pointing everyone to my local machine.
I need to point a TV at the installation running on my local machine. Another project would be wanting to point to their installation. Another user, e.g. Jenkins running continuous integration may want to be pointed at a different installation again.
Or do you mean we need to set up DNS servers on each local machine?

**Comment by andyburras** [comment]
Got it. So I just need to enter the <explicit IP address>:8050 on the device. I don't need the web-platform part.

**Comment by squapp** [comment]
note that by not using the domain name, the subdomain/dns test cases will most likely fail.
If you cannot change the DNS settings on a device, you will need to point the DUT to a DNS server (e.g. in a local network) which maps the domain name to the IP of the machine that is hosting the test suite

**Comment by squapp** [comment]
Closing this, because 'manual', 'visual' type tests were not supported for WMATS2017
