### ISSUE TITLE
Crashes whilst running full test set on TV

### ISSUE THREAD

**Issue by andyburras** [cta-wave/WMAS2017#25]
Attempting to run a locally hosted instance on the internet web browser of a recent leading TV resulted in browser crashes around 85% through the test run. Restarting the test run from the last point succeeded twice, but the browser crashed again after a short time.
Tests failed at:
"TIMEOUT html/infrastructure/urls/terminology-0/multiple-base.sub.html"
. . .
TIMEOUT workers/semantics/structured-clone/dedicated.html
. . .
TIMEOUT content-security-policy/reporting-api/reporting-api-doesnt-send-reports-without-violation.https.sub.html"
See attached screenshots.

![20181016_170116](https://user-images.githubusercontent.com/28623246/47142849-c2940d00-d2bb-11e8-9464-ed1bc1d64475.jpg)
![20181016_170338](https://user-images.githubusercontent.com/28623246/47142850-c2940d00-d2bb-11e8-9348-c5bf911f6974.jpg)
![20181017_095745](https://user-images.githubusercontent.com/28623246/47142852-c32ca380-d2bb-11e8-8a1e-a0d1a613df2e.jpg)

My suspicion is that the browser is running out of memory as the test run progresses.
(possibly compounded by https://github.com/cta-wave/WMAS2017/issues/19 as we are having to run all tests, not the subset).

**Comment by squapp** [comment]
could you try the hosted test suite instance, which runs the subset?
