### ISSUE TITLE
WMAS2017 not running all tests that pass on all 4 browsers

### ISSUE THREAD

**Issue by andyburras** [cta-wave/WMAS2017#26]
Attempting to run the CSS visufx tests locally on the latest Firefox, with http://web-platform.test:8050/?path=/css/CSS2/visufx
The test suite is running zero tests (see attached):

![visufx_wave](https://user-images.githubusercontent.com/28623246/47295637-0c585c80-d608-11e8-8d75-3f31e2c13f04.jpg)

However, looking on the W3C dashboard https://wpt.fyi/results/css/CSS2/visufx shows that 49 of the 51 tests passed on all four browsers. (see attached):

![visufx_w3c](https://user-images.githubusercontent.com/28623246/47295624-fc407d00-d607-11e8-88b4-cfa31d553c64.jpg)

Similarly if selecting the 'css' option, and 'all browsers' on http://webapitests2017.ctawave.org:8050 , these visufx tests are not run.

**Comment by squapp** [comment]
I think this is related to #27 and #20 
These test cases look like "visual" tests and therefore require manual interaction. We have excluded these for the same reasons as "manual" tests

**Comment by squapp** [comment]
Closing this, because 'manual', 'visual' type tests were not supported for WMATS2017
