### ISSUE TITLE
No support for "visual" tests

### ISSUE THREAD

**Issue by andyburras** [cta-wave/WMAS2017#27]
According to https://web-platform-tests.org/writing-tests/ there are four main test types: 

- Reftests - should be used to test rendering and layout. They consist of two or more pages with assertions as to whether they render identically or not. 
- testharness.js - tests should be used (where possible!) for testing everything else. They are built with the testharness.js unit testing framework, and consist of assertions written in JavaScript. 
- Visual tests - should be used for checking rendering where there is a large number of conforming renderings such that reftests are impractical. They consist of a page that renders to final state at which point a screenshot can be taken and compared to an expected rendering for that user agent on that platform. 
- Manual tests - are used as a last resort for anything that can’t be tested using any of the above. They consist of a page that needs manual interaction or verification of the final result. 

The WMAS2017 test suite looks to be only supporting "_Possible types: testharness, manual and reftest_". It doesn't seem possible to run the "visual" tests? Or are these combined with the "manual" type when run on cta-wave?

**Comment by squapp** [comment]
Closing this, because 'manual', 'visual' type tests were not supported for WMATS2017
