### ISSUE TITLE
Cannot review test scripts in report

### ISSUE THREAD

**Issue by paulhiggs** [cta-wave/WMAS2017#3]
When looking at the test report we see the following as an example
![image](https://user-images.githubusercontent.com/3158807/43259592-bbf5dad6-90a4-11e8-98b8-36bfa85be425.png)

The links refer to each w3c test file, but clicking them opens and executes the test in a browser tab. It would be more useful if the newly opened browser tab showed the text of the test script. This report is being viewed on an "office PC" and not a DUT so does not need to run any tests

**Comment by mlasak** [comment]
That's a bug. We need to fix the incorrect links. Thanks.

**Comment by mlasak** [comment]
We discussed this one. Current plan is to create a branch on this repository that includes all the tests of the snapshot and we'll change the links in the report to point to this tests. This will allow for reviews of the test scripts with specific version.

**Comment by mlasak** [comment]
Fixed.
