### ISSUE TITLE
Test report formatting 2

### ISSUE THREAD

**Issue by paulhiggs** [cta-wave/WMAS2017#5]
The test report shows some "conflicting" results..
![image](https://user-images.githubusercontent.com/3158807/43265541-074e1734-90b7-11e8-9b87-f88156e4b99f.png)

If the test was NOTRUN for some reason, then it probably did not TIMEOUT

**Comment by louaybassbouss** [comment]
we will check also this similar to issue #4

**Comment by louaybassbouss** [comment]
@paulhiggs please refer to issue #4 for a description of each status.

For this issue, the sub test is still in status `NOTRUN` (for some reason) and the overall status will be set to `TIMEOUT` by the server which then continues to run the next test file.

**Comment by paulhiggs** [comment]
@louaybassbouss thanks for the description both here and in issue #4 
I'm still not sure I follow the logic here but would only expect to see "NOTRUN" at the test level if this test - and all the subtests were skipped. Seeing TIMEOUT for the test and NOTRUN for the one and only subtest means that the overall test status was NOTRUN.

If possible, I would only retain the status on the individual tests. It makes it easier to scan through the test report looking for anything that is a problem. In this regard, i would consider TIMEOUT as a problem as it means that the test was supposed to run but did not fully execute and was terminated.

**Comment by louaybassbouss** [comment]
Thanks @paulhiggs we will only retain the status of individual tests in the test report. We will let you know.
