### ISSUE TITLE
WMAS 2021 Test Suite Redirect

### ISSUE THREAD

**Issue by JohnRiv** [cta-wave/WMAS2017#79]
[WMAS2021](https://www.w3.org/2021/12/webmediaapi.html) references https://webapitests2021.ctawave.org/wave/, but that URL currently returns:
```
{"error": {"code": 404, "message": "404"}}
```

Please redirect https://webapitests2021.ctawave.org/wave/ to https://webapitests2021.ctawave.org/_wave/index.html (or host the 2021 test suite at https://webapitests2021.ctawave.org/wave/ )

**Comment by louaybassbouss** [comment]
@JohnRiv this is fixed now, feel free to close the issue

**Comment by JohnRiv** [comment]
Thanks! Confirmed https://webapitests2021.ctawave.org/wave/ is 301 redirecting to https://webapitests2021.ctawave.org/_wave/index.html
